### ISSUE TITLE
QUnit - Better diff output

### ISSUE THREAD

**Issue by gauravmittal1995** [jquery/qunit#774] opened 2015-03-10 19:18 UTC
For the GSoC project "QUnit - Better diff output", what are the requirements and details??

Any other issues apart the ones mentioned in https://github.com/jquery/qunit/issues/364 ???

@leobalter @jzaefferer Please advice.

**Comment by jzaefferer** [comment] 2015-03-10 19:49
#364 is our meta ticket for the topic, that's definitely the best reference.

One thing not mentioned there, that came up with the recent PRs: We should have better tests for diffs. The ones you screenshotted in #764 are a good starting point. A visual test page (failing tests?) would be good for manual, visual verification. Automated tests that somehow prevent regressions would also help, maybe by checking the length of a diff, ensuring that changes to the diff don't make it worse (if longer always means worse).

Another idea: Do some research across JS testing frameworks. See what others to about diffing, if at all. See if we should (eventually) extract our diff module into a standalone module, that other frameworks could use. Should find at least two frameworks actually interested in that before making any changes on our end.

That's two additional tasks I can think of right now. There's probably more.

I'm assuming you're asking this to write your proposal. If you need a reference, [this one](https://gist.github.com/tanay1337/484daa8bb8410bcb607a) (for jQuery UI) seems pretty decent to me.

**Comment by gauravmittal1995** [comment] 2015-03-10 20:17
@jzaefferer Do i make a proposal and put it on gist as well??

**Comment by jzaefferer** [comment] 2015-03-10 20:18
Sure, that way we can review it before the official submission process starts. Doesn't have to be a gist, anything you can share with us should work.

PS: One question mark is enough ;-)

**Comment by gauravmittal1995** [comment] 2015-03-10 20:20
@jzaefferer Thanks :-D

**Comment by gauravmittal1995** [comment] 2015-03-10 23:27
@jzaefferer @leobalter Hey, I have a doubt in the proposal. How do i make my timeline. I dont know how much time each task could take. How do i decide that?

**Comment by shivamdixit** [comment] 2015-03-11 01:23
@jzaefferer I've two questions in my mind:

1. For the GSOC project do we need to improve the current diff algorithm of @jeresig or as the other tickets suggest that we can use some already existing libraries for diff?

2. If we are using already existing library I'm not sure why we should extract that module into standalone module (It's already there)?

Thanks.

**Comment by jzaefferer** [comment] 2015-03-11 12:46
@gauravmittal1995 take the time since you started your first PR to landing it (you may need to extrapolate that, since its still open). Then multiply that by two and you have a rough estimate. Or just guess. Or assume one week per task. Don't worry too much about it, time estimates are never something to stick strict deadlines to.

@shivamdixit check out #772, that should answer both your questions.

**Comment by gauravmittal1995** [comment] 2015-03-11 12:48
@jzaefferer Thanks

**Comment by jzaefferer** [comment] 2015-05-18 15:30
Closing this since there's nothing to discuss here and the underlying diff-related issues are enough.

**Closed by jzaefferer** 2015-05-18 15:30 UTC
Labels: diff
