### ISSUE TITLE
Never ending async test although `done` was called

### ISSUE THREAD

**Issue by vogdb** [jquery/qunit#1018] opened 2016-06-29 18:00 UTC
I guess that I am super unlucky. Test hangs and `afterEach` is never called. Bugs on 2.0.0. Works fine on 1.23.1.
```js
QUnit.module('Sample tests', {
  beforeEach: function() {
    console.log('`beforeEach` started');
    return new Promise(function(resolve) {
      setTimeout(function() {
        console.log('`beforeEach` complete');
        resolve();
      }, 100);
    });
  },
  afterEach: function() {
    console.log('`afterEach` started');
    return new Promise(function(resolve) {
      setTimeout(function() {
        console.log('`afterEach` complete');
        resolve();
      }, 100);
    });
  }
});

QUnit.test('Sample test', function(assert) {
  console.log('Test started!');
  //assert.expect(1);
  var done = assert.async();
  setTimeout(function(){
    assert.ok(true);
    console.log('Test finished!');
    done();
  }, 1000);
});
```

**Comment by leobalter** [comment] 2016-06-29 18:08
bug confirmed, but I guess the cause might be the same as in #1016.

**Comment by trentmwillis** [comment] 2016-06-29 19:33
Can confirm that this is related. Marking as duplicate and closing. We can use the other issue to track, I'm working on a fix.

**Closed by trentmwillis** 2016-06-29 19:33 UTC
Labels: bug
