### ISSUE TITLE
`jscs task` normally doesn`t working.

### ISSUE THREAD

**Issue by mixed** [jquery/qunit#917] opened 2016-01-08 07:38 UTC
`jscs task` doesn't normally working because `grunt-jscs` version is low. `jscs task` is normally working when  `grunt-jscs` version up.

Ref #916

**Comment by leobalter** [comment] 2016-01-13 16:28
we need to update our grunt jscs and jshint tasks.

This is a duplicate of #879.

@mixed, would you like to help on this one as well? It's more than just updating the packages, but also fixing some code styles.

**Closed by leobalter** 2016-01-13 16:28 UTC

**Comment by mixed** [comment] 2016-01-13 16:47
@leobalter 
Ah.. OK.
If @arghgr don't mind it I can it. package update, fixing some code styles.
