### ISSUE TITLE
Remove QUnit.stop, update QUnit.start to only work globally

### ISSUE THREAD

**Issue by JamesMGreene** [jquery/qunit#655] opened 2014-09-05 16:01 UTC
Related to #653.

In QUnit `v2.0.0`:
 - `QUnit.start` will be updated to only affect the run's initial blocking state as controlled by `QUnit.config.autostart`. It will no longer control asynchronous flow inside of Test callbacks.
 - `QUnit.stop` will be removed completely. It will no longer control asynchronous flow inside of Test callbacks, nor be allowed to affect the run's blocking state.

**Comment by spocke** [comment] 2015-09-24 13:13
Please don't remove QUnit.stop(); we use it in a case where each module stop:s waits for an editor to initialize then calls QUnit.start(); to run the tests. Instead I suggest that QUnit.stop remains but that it only works outside a test context.

Currently I can't update QUnit to the latest version due to the error being thrown from QUnit,stop.

**Comment by leobalter** [comment] 2015-09-24 14:59
`QUnit.stop()` is deprecated but it should work just fine on every QUnit.1.x.x versions.

If you have an error on `QUnit.stop` you should check if it's not an implementation error or a regression.

Which version you use today?

**Comment by platinumazure** [comment] 2016-04-10 17:10
Is `QUnit.start()` still supported for restarting tests after an error, where async callbacks might be out of scope? (See [test.js](https://github.com/jquery/qunit/blob/f13038f8530da11a4c3793f35ffe4d4e1d0531a2/src/test.js#L121-123) for an example)

**Comment by leobalter** [comment] 2016-04-11 13:57
@platinumazure that's a good question. I'll keep this in mind and have tests for what ever way it will work. Makes sense to keep this behavior.

**Comment by platinumazure** [comment] 2016-04-11 15:30
For what it's worth, I'd be okay with the method being deprecated and a new one being created, if that makes things make more sense semantically. I just need the ability for error handlers to restart tests under certain circumstances.

**Comment by leobalter** [comment] 2016-04-12 17:56
@platinumazure I agree, but that would require introducing a new method (maybe `QUnit.run`) and than deprecate `QUnit.start`. That would have `QUnit.start` being removed on 3.x as it's too late to introduce a new feature for 2.0.

**Closed** 2016-04-18 16:09 UTC
Labels: api
